/**
 * @file app/api/assistant/route.ts
 *
 * Streams a Black Tier Circle assistant reply from Claude.
 *
 * @module Api
 */

import { requireRole } from '@/lib/auth/session';
import { AppError } from '@/lib/errors';
import { handleRouteError, readJsonBody } from '@/lib/http';
import { z } from 'zod';

export const dynamic = 'force-dynamic';

const SYSTEM_PROMPT = `You are the AI assistant for Black Tier Circle, a multi-tenant Telegram reseller platform for digital products.

You help resellers and the platform owner with:
- Setting up and connecting Telegram bots
- Managing products and pricing
- Understanding wallet and payment flows
- Using the API and webhooks
- Troubleshooting common issues
- Understanding how the platform works

Key facts about Black Tier Circle:
- Resellers connect their own Telegram bots via BotFather token
- Owner adds products, resellers set their own margins
- Payments: USDT BEP20, Binance Pay, or wallet balance
- Products are sourced from connected supplier APIs or added manually
- Wallet top-up: 12-digit tokens generated by owner
- Resellers pay wholesale price, earn the margin

Platform URL: https://blacktiercircle.vercel.app
API docs: https://blacktiercircle.vercel.app/api-docs

Always be helpful, concise, and specific to the Black Tier Circle platform.
If you don't know something specific to this user's account, say so and suggest they check their dashboard or contact the owner.`;

const BodySchema = z.object({
  messages: z
    .array(
      z.object({
        role: z.enum(['user', 'assistant']),
        content: z.string().trim().min(1).max(4000),
      }),
    )
    .min(1)
    .max(20),
});

export async function POST(request: Request): Promise<Response> {
  try {
    await requireRole(['owner', 'reseller']);
    const body = BodySchema.parse(await readJsonBody(request));
    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      throw new AppError('ASSISTANT_UNAVAILABLE', 'Add ANTHROPIC_API_KEY to enable the assistant', 503);
    }

    const upstream = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-6',
        max_tokens: 1024,
        stream: true,
        system: SYSTEM_PROMPT,
        messages: body.messages,
      }),
    });

    if (!upstream.ok || upstream.body === null) {
      const detail = await upstream.text();
      throw new AppError('ASSISTANT_FAILED', detail.slice(0, 180) || 'Assistant request failed', 502);
    }

    return new Response(upstream.body, {
      headers: {
        'Content-Type': 'text/event-stream; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    });
  } catch (error: unknown) {
    return handleRouteError(error);
  }
}
