/**
 * @file app/api/assistant/route.ts
 *
 * Streams a Black Tier Circle assistant reply from Grok.
 *
 * @module Api
 */

import { asDbClient, requireReseller, requireRole } from '@/lib/auth/session';
import { AppError } from '@/lib/errors';
import {
  recallCustomerExperience,
  resolveCustomerMemoryBank,
  retainCommerceExperience,
  type MemoryEvidence,
} from '@/lib/hindsight';
import { DEMO_CUSTOMER_ID, DEMO_TENANT_ID } from '@/lib/intelligence-demo';
import { handleRouteError, readJsonBody } from '@/lib/http';
import { getTenantByUserId } from '@/modules/tenants';
import { z } from 'zod';

export const dynamic = 'force-dynamic';

const SYSTEM_PROMPT = `You are the AI assistant for Black Tier Circle, a multi-tenant Telegram reseller platform for digital products.

You help resellers and the platform owner with:
- Setting up and connecting Telegram bots
- Managing products and pricing
- Understanding wallet and payment flows
- Using the API and webhooks
- Troubleshooting common issues
- Understanding how the platform works

Key facts about Black Tier Circle:
- Resellers connect their own Telegram bots via BotFather token
- Owner adds products, resellers set their own margins
- Payments: USDT BEP20, Binance Pay, or wallet balance
- Products are sourced from connected supplier APIs or added manually
- Wallet top-up: 12-digit tokens generated by owner
- Resellers pay wholesale price, earn the margin

Platform URL: https://blacktiercircle.vercel.app
API docs: https://blacktiercircle.vercel.app/api-docs

Always be helpful, concise, and specific to the Black Tier Circle platform.
If you don't know something specific to this user's account, say so and suggest they check their dashboard or contact the owner.`;

const BodySchema = z.object({
  messages: z
    .array(
      z.object({
        role: z.enum(['user', 'assistant']),
        content: z.string().trim().min(1).max(4000),
      }),
    )
    .min(1)
    .max(20),
});

export async function POST(request: Request): Promise<Response> {
  try {
    const session = await requireRole(['owner', 'reseller']);
    const body = BodySchema.parse(await readJsonBody(request));
    const apiKey = process.env.GROQ_API_KEY;
    if (!apiKey) {
      throw new AppError('ASSISTANT_UNAVAILABLE', 'Add GROQ_API_KEY to enable the assistant', 503);
    }

    const userMessage = [...body.messages].reverse().find((message) => message.role === 'user')?.content ?? '';
    const memory = await loadCustomerMemory(session, userMessage);
    const system = memory.memories.length > 0
      ? `${SYSTEM_PROMPT}\n\nCustomer memory context (use this to personalize your response):\n${memory.memories
          .slice(0, 5)
          .map((item) => `- ${item.text}`)
          .join('\n')}`
      : SYSTEM_PROMPT;

    const upstream = await fetch('https://api.x.ai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'grok-3',
        max_tokens: 1024,
        stream: true,
        messages: [{ role: 'system', content: system }, ...body.messages],
      }),
    });

    if (!upstream.ok || upstream.body === null) {
      const detail = await upstream.text();
      throw new AppError('ASSISTANT_FAILED', detail.slice(0, 180) || 'Assistant request failed', 502);
    }

    const memoryPowered = memory.memories.length > 0;
    const prelude = `data: ${JSON.stringify({
      type: 'memory_context',
      memoryPowered,
      memories: memory.memories.slice(0, 5).map((item) => ({ text: item.text })),
    })}\n\n`;
    const encoder = new TextEncoder();
    const reader = upstream.body.getReader();
    const decoder = new TextDecoder();
    let buffer = '';
    let aiResponse = '';
    const stream = new ReadableStream<Uint8Array>({
      async start(controller) {
        controller.enqueue(encoder.encode(prelude));
        try {
          for (;;) {
            const chunk = await reader.read();
            if (chunk.done) {
              break;
            }
            buffer += decoder.decode(chunk.value, { stream: true });
            const lines = buffer.split('\n');
            buffer = lines.pop() ?? '';
            for (const line of lines) {
              const trimmed = line.trim();
              if (!trimmed.startsWith('data:')) {
                continue;
              }
              const payload = trimmed.slice(5).trim();
              if (!payload || payload === '[DONE]') {
                continue;
              }
              try {
                const event = JSON.parse(payload) as {
                  choices?: Array<{ delta?: { content?: string } }>;
                };
                const text = event.choices?.[0]?.delta?.content;
                if (typeof text !== 'string' || text.length === 0) {
                  continue;
                }
                aiResponse += text;
                controller.enqueue(
                  encoder.encode(
                    `data: ${JSON.stringify({ type: 'content_block_delta', delta: { text } })}\n\n`,
                  ),
                );
              } catch {
                // Ignore keep-alive lines from the upstream stream.
              }
            }
          }
          controller.close();
        } catch (error: unknown) {
          controller.error(error);
        } finally {
          if (memory.bankId) {
            void retainCommerceExperience(
              memory.bankId,
              `chat-${Date.now()}`,
              `Customer asked: ${userMessage.slice(0, 200)} | Response summary: ${aiResponse.slice(0, 200)}`,
              ['kind:support_resolution'],
              { channel: 'chatbot' },
            ).catch(() => undefined);
          }
        }
      },
    });

    return new Response(stream, {
      headers: {
        'Content-Type': 'text/event-stream; charset=utf-8',
        'Cache-Control': 'no-store',
        'X-Memory-Powered': memoryPowered ? 'true' : 'false',
      },
    });
  } catch (error: unknown) {
    return handleRouteError(error);
  }
}

async function loadCustomerMemory(
  session: Awaited<ReturnType<typeof requireRole>>,
  userMessage: string,
): Promise<{ bankId: string | null; memories: MemoryEvidence[] }> {
  let tenantId: string | null = null;
  const customerId = session.user.id;
  try {
    if (session.profile.role === 'reseller') {
      const reseller = await requireReseller();
      tenantId = reseller.tenant.id;
    } else {
      const tenant = await getTenantByUserId(asDbClient(session.admin), session.user.id);
      tenantId = tenant.id;
    }
  } catch {
    tenantId = null;
  }

  if (tenantId && userMessage.trim().length > 0) {
    const bankId = resolveCustomerMemoryBank(tenantId, customerId);
    try {
      const memories = await recallCustomerExperience(bankId, userMessage);
      if (memories.length > 0) {
        return { bankId, memories };
      }
    } catch {
      // Memory lookup must not block the assistant.
    }
  }

  if (process.env.NODE_ENV !== 'production' && userMessage.trim().length > 0) {
    const bankId = resolveCustomerMemoryBank(DEMO_TENANT_ID, DEMO_CUSTOMER_ID);
    try {
      const memories = await recallCustomerExperience(bankId, userMessage);
      if (memories.length > 0) {
        return { bankId, memories };
      }
    } catch {
      return { bankId: null, memories: [] };
    }
  }

  return { bankId: tenantId ? resolveCustomerMemoryBank(tenantId, customerId) : null, memories: [] };
}
